{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Status_error",
   "type": "stat",
   "description": "количество ошибок запросов к серверу",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_status_total{status=\"422\"}",
     "legendFormat": "4** error"
    },
    {
     "expr": "http_request_status_total{status=\"500\"}",
     "legendFormat": "5** error"
    }
   ]
  },
  {
   "title": "Rate status request",
   "type": "timeseries",
   "description": "Показывает количество запросов в минуту",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_status_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Prediction values",
   "type": "timeseries",
   "description": "Распределение значений предсказаний.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(model_prediction_values_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU seconds total",
   "type": "stat",
   "description": " Показывает, сколько CPU использует процесс в контейнере.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Virtual memory bytes",
   "type": "table",
   "description": " Показывает, сколько CPU использует процесс в контейнере.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 16 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Memory bytes" }
   ]
  }
 ]
}