version: "3.9"

services:
  ml_service:
    build:
      context: ./ml_service
    image: ml_service_image:2
    container_name: ml_service_container
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models

  request_sender:
    build:
      context: ./requests
    image: request_sender_image:1
    container_name: request_sender_container
    depends_on:
      - ml_service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - ml_service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus